#!/bin/sh

curl -sL https://github.com/upfluence/etcdenv/releases/download/v0.2.1/etcdenv-linux-amd64-0.2.1 \
 > etcdenv

GOOS=linux CGO_ENABLED=0 GOARCH=amd64 go build -o sensu-aws-client

docker build -t upfluence/sensu-aws-client:latest .
docker push upfluence/sensu-aws-client
